# Generated by Django 3.1.14 on 2023-04-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonentity',
            name='defence',
            field=models.ImageField(default=3, upload_to=''),
        ),
        migrations.AddField(
            model_name='pokemonentity',
            name='health',
            field=models.ImageField(default=3, upload_to=''),
        ),
        migrations.AddField(
            model_name='pokemonentity',
            name='level',
            field=models.ImageField(default=3, upload_to=''),
        ),
        migrations.AddField(
            model_name='pokemonentity',
            name='stamina',
            field=models.ImageField(default=3, upload_to=''),
        ),
        migrations.AddField(
            model_name='pokemonentity',
            name='strength',
            field=models.ImageField(default=3, upload_to=''),
        ),
    ]
